# Generated by Django 3.2.4 on 2021-06-19 04:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('mobile', 'Mobile'), ('computer', 'Computer'), ('hardware', 'Hardware'), ('programming', 'Programming')], max_length=144)),
                ('category_image', models.ImageField(default='default.jpg', upload_to='article/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_tag', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', tinymce.models.HTMLField()),
                ('article_short_text', tinymce.models.HTMLField()),
                ('article_image', models.ImageField(default='default.jpg', upload_to='article/')),
                ('article_upload_date', models.DateField()),
                ('article_writer', models.CharField(max_length=21)),
                ('article_long_text', tinymce.models.HTMLField()),
                ('article_category', models.ForeignKey(default='-', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.category')),
                ('article_tag', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
