# Generated by Django 3.2.4 on 2021-06-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='default.jpg', upload_to='article'),
        ),
    ]
