# Generated by Django 3.2.4 on 2021-06-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('boys', 'Boys'), ('girls', 'Girls'), ('unisex', 'Unisex')], max_length=34, null=True)),
                ('gender_image', models.ImageField(default='default.jpg', upload_to='product/gender')),
            ],
        ),
    ]
