# Generated by Django 3.2.4 on 2021-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender_name',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('boys', 'Boys'), ('girls', 'Girls'), ('unisex', 'Unisex')], max_length=34, null=True),
        ),
    ]
