# Generated by Django 3.2.2 on 2021-05-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('short_text', models.TextField(default='-')),
                ('long_text', models.TextField(default='-')),
                ('category', models.TextField(default='-')),
                ('category_id', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('publish_date', models.CharField(default='-', max_length=13)),
                ('picture', models.CharField(default='-', max_length=21)),
                ('writer', models.CharField(default='-', max_length=21)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
