# Generated by Django 3.2.2 on 2021-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.TextField(),
        ),
    ]
