# Generated by Django 3.2.2 on 2021-05-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='picture',
            new_name='picture_name',
        ),
        migrations.AddField(
            model_name='news',
            name='picture_url',
            field=models.TextField(default='-'),
        ),
    ]
