# Generated by Django 3.2.2 on 2021-05-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210519_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_time',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
