# Generated by Django 3.2.4 on 2021-06-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, choices=[('cardigan', 'Cardigan'), ('pullover', 'Pullover'), ('vest', 'Vest')], max_length=34, null=True)),
                ('category_image', models.ImageField(default='default.jpg', upload_to='product/category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
