# Generated by Django 3.2.4 on 2021-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('cardigan', 'Cardigan'), ('pullover', 'Pullover'), ('vest', 'Vest')], max_length=34)),
                ('category_image', models.ImageField(default='default.jpg', upload_to='product/category')),
            ],
        ),
    ]
