# Generated by Django 3.2.4 on 2021-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_categogy_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, choices=[('cardigan', 'Cardigan'), ('pullover', 'Pullover'), ('vest', 'Vest')], max_length=34, null=True),
        ),
    ]
