# Generated by Django 3.2.4 on 2021-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_style', models.TextField(max_length=21)),
                ('product_composition', models.TextField(max_length=144)),
                ('product_gauge', models.TextField(max_length=13)),
                ('product_size', models.TextField(max_length=13)),
                ('product_weight', models.TextField(max_length=13)),
                ('product_moq', models.TextField(max_length=13)),
                ('product_fob', models.TextField(max_length=13)),
                ('product_merchant', models.IntegerField(default=0)),
                ('product_buyer', models.IntegerField(default=0)),
                ('product_shipment_date', models.DateTimeField()),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_image', models.ImageField(default='default.jpg', upload_to='product/pro')),
                ('product_chart', models.ImageField(default='default.jpg', upload_to='product/chart')),
            ],
        ),
    ]
