# Generated by Django 3.2.4 on 2021-06-12 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('gender', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_style', models.CharField(max_length=21)),
                ('product_composition', models.CharField(max_length=144)),
                ('product_gauge', models.CharField(max_length=13)),
                ('product_size', models.CharField(max_length=13)),
                ('product_weight', models.CharField(max_length=13)),
                ('product_moq', models.CharField(max_length=13)),
                ('product_fob', models.CharField(max_length=13)),
                ('product_buyer', models.IntegerField(default=0)),
                ('product_shipment_date', models.DateField()),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_image', models.ImageField(default='default.jpg', upload_to='product/pro')),
                ('product_chart', models.ImageField(default='default.jpg', upload_to='product/chart')),
                ('product_category', models.ForeignKey(default='-', on_delete=django.db.models.deletion.SET_DEFAULT, to='category.category')),
                ('product_gender', models.ForeignKey(default='-', on_delete=django.db.models.deletion.SET_DEFAULT, to='gender.gender')),
                ('product_merchant', models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.SET_DEFAULT, to='merchant.merchant')),
            ],
        ),
    ]
