# Generated by Django 3.2.4 on 2021-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_composition',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fob',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gauge',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_moq',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_shipment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_style',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.CharField(max_length=13),
        ),
    ]
