# Generated by Django 3.2.4 on 2021-06-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210606_0920'),
        ('gender', '0002_alter_gender_gender_name'),
        ('product', '0002_auto_20210605_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender'),
        ),
    ]
