# Generated by Django 3.2.4 on 2021-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=55)),
                ('merchant_designation', models.CharField(max_length=55)),
                ('merchant_mobile', models.CharField(max_length=21)),
                ('merchant_email', models.EmailField(max_length=254)),
                ('merchant_join_date', models.DateField()),
                ('merchant_image', models.ImageField(default='default.jpg', upload_to='product/merchant')),
            ],
        ),
    ]
