# Generated by Django 3.2.2 on 2021-05-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='contact',
            field=models.CharField(default='-', max_length=21),
        ),
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=21),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=21),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=21),
        ),
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(default='-', max_length=21),
        ),
    ]
